---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remo
  template:
    metadata:
      labels:
        app: remo
    spec:
      containers:
        - image: itlinux/simple-argo:main
        name: simple
        ports:
        - containerPort: 80
